export const styles = {
  page: {
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    minHeight: '100vh',
    width: '100vw',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'flex-start',
    margin: '0',
    padding: '0',
  },
  content: {
    marginTop: '20px',
    width: '80%',
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: '8px',
    boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.1)',
    padding: '20px',
    textAlign: 'center' as const,
  },
  header: {
    display: 'flex',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    padding: '0px',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    boxShadow: '1px 5px 5px rgba(0, 0, 0, 0.2)',
    margin: '2px',
    borderRadius: '15px',
  },
  logo: {
    padding: '10px',
    textAlign: 'end' as const,
    textDecoration: 'none',
    lineHeight: '0',
  },
  menu: {
    padding: '20px',
    paddingRight: '40px',
    textAlign: 'end' as const,
    color: 'black',
    textDecoration: 'none',
  },
  display: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '2px',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '5px',
    borderRadius: '8px',
    boxShadow: '0px 2px 5px rgba(0, 0, 0, 0.1)',
    marginBottom: '8px',
  },
  ball: {
    backgroundColor: 'rgba(35, 187, 29, 0.88)',
    color: 'white',
    padding: '5px 10px',
    marginRight: '10px',
    fontSize: '20px',
    fontWeight: 'bold',
    border: 'none',
    borderRadius: '20px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
};